
# DE - Differential Expression

## DE Analysis

We need to prepare the dds objects in order to be sure we obtain the wished contrasts, and then perform the differential expression analysis with the DESeq2 package. We can see which object can be used to obtain which contrasts.

```{r de-analysis, echo = FALSE}
# if not load dds objects 
if (!purrr::pluck(params, "load_dds_objects", .default = FALSE)){

  # releveling
  dds$group <- relevel(dds[[factor_columns[[1]]]], "ctrl")

  # de analysis
  dds <- DESeq(dds)

  # dds_releveled <- dds
  # dds_releveled$group <- relevel(dds_releveled$group, "")
  # dds_releveled <- nbinomWaldTest(dds_releveled)
}
```

```{r contrasts}
# contrasts
(contrasts_main <- resultsNames(dds))
```
```{r contrasts-releveled, eval = FALSE, include = FALSE}
# contrasts
(contrasts_releveled <- resultsNames(dds_releveled))
```

## DE Parameters

```{r FDR}
# set FDR 
FDR = 0.1 # false discovery rate
```

```{r myresuSet,  include = FALSE}
if (!exists("myresuSet")) myresuSet <- list() # create if not loaded
```

## Contrasts

<!-- <details>

<summary>click here to display DE results of </summary> -->

```{r initialize-de-tables, echo = FALSE,include = FALSE}
# You need this code to conduct the magic dependences attaching...
DT::datatable(matrix())
```


```{r de-tables, results = 'asis', echo = FALSE}

for (contrast in contrasts) {

  dds_to_use <- dds
  # if (grepl("", contrast)) dds_to_use <- dds_releveled else dds_to_use <- dds # If you use a releveled object you cchange this line
 
 
  if (!purrr::pluck(params, "load_dds_objects", .default = FALSE)) {
    myresuSet <- alltheresults(
      myresuSet, dds_to_use,
      contrast = c(contrast), FDR = FDR,
      anno_df = anno_df, anns = anns, species = purrr::pluck(params, "species", .default = "Mm")
    )
  }
    if (is.null(myresuSet[[contrast]]$etbl_res_DE)) {
      cat(paste0("No differentially expressed genes found for contrast ", contrast, ". Consider increasing the FDR threshold."))
    } else {
      cat(knitr::knit_print(DT::datatable(
        myresuSet[[contrast]]$etbl_res_DE,
        escape = FALSE,
        rownames = FALSE,
        caption = htmltools::tags$caption(
          style = 'caption-side: top; color:black;; font-size: 2em',
          contrast
        )
      )))
    }
}
rm(dds_to_use)
```

```{r de-tables-no-report, results = 'asis', echo = FALSE, eval = FALSE, include = FALSE}
# Run this if you are not generating a report
for (contrast in contrasts) {

  dds_to_use <- dds
  # if (grepl("", contrast)) dds_to_use <- dds_releveled else dds_to_use <- dds # If you use a releveled object you cchange this line
 
 if (!purrr::pluck(params, "load_dds_objects", .default = FALSE))
    myresuSet <- alltheresults(
      myresuSet, dds_to_use,
      contrast = c(contrast), FDR = FDR,
      anno_df = anno_df, anns = anns, species = purrr::pluck(params, "species", .default = "Mm"))
    # myresuSet[[contrast]]$maplot_res
    if (is.null(myresuSet[[contrast]]$etbl_res_DE)) {
      cat(paste0("No differentially expressed genes found for contrast ", contrast, ". Consider increasing the FDR threshold."))
    } else {
      print(DT::datatable(myresuSet[[contrast]]$etbl_res_DE, escape = FALSE, rownames = FALSE, 
          caption = htmltools::tags$caption(style = 'caption-side: top; color:black;; font-size: 2em', contrast)))
    }
}
rm(dds_to_use)
```

