
## DE Parameters

```{r FDR}
# set FDR 
FDR = 0.1 # false discovery rate
```

```{r myresuSet,  include = FALSE}
if (!exists("myresuSet")) myresuSet <- list()
```

## Contrasts

You can select for which contrasts to see the DE results, to do this you can copy the following blocks as many times as you want and add the correct contrast name. The correct object also needs to be chosen.

## finerenone_contrasts

<!-- <details>

<summary>click here to display DE results of </summary> -->

```{r, echo = FALSE,include = FALSE}
# You need this code to conduct the magic dependences attaching...
DT::datatable(matrix())
```


```{r, results = 'asis', echo = FALSE}

for (contrast in finerenone_contrasts) {
  if (grepl("AT2$", contrast)) dds_to_use <- dds_releveled else dds_to_use <- dds
  if (!purrr::pluck(params, "load_dds_objects", .default = FALSE))
    myresuSet <- alltheresults(
      myresuSet, dds_to_use,
      contrast = c(contrast), FDR = FDR,
      anno_df = anno_df, anns = anns, species = "Mus_musculus")
  # myresuSet[[contrast]]$maplot_res
    cat(knitr::knit_print(DT::datatable(myresuSet[[contrast]]$etbl_res_DE, escape = FALSE, rownames = FALSE, 
        caption = htmltools::tags$caption(style = 'caption-side: top; color:black;; font-size: 2em', contrast))))
}
rm(dds_to_use)
```



## sglt2_contrasts

```{r, results = 'asis', echo = FALSE}

for (contrast in sglt2_contrasts) {
  if (grepl("AT2$", contrast)) dds_to_use <- dds_releveled else dds_to_use <- dds
  if (!purrr::pluck(params, "load_dds_objects", .default = FALSE))
    myresuSet <- alltheresults(
      myresuSet, dds_to_use,
      contrast = c(contrast), FDR = FDR,
      anno_df = anno_df, anns = anns, species = "Mus_musculus")
  # myresuSet[[contrast]]$maplot_res
    cat(knitr::knit_print(DT::datatable(myresuSet[[contrast]]$etbl_res_DE, escape = FALSE, rownames = FALSE, 
        caption = htmltools::tags$caption(style = 'caption-side: top; color:black; font-size: 2em', contrast))))
}
rm(dds_to_use)
```
