source("helper_functions/alltheresults.r")
source("helper_functions/annotation_datasets.r")
source("helper_functions/enrichment_map_test.r")
source("helper_functions/install_if_missing.r")
source("helper_functions/prepare_workspace.r")
source("helper_functions/resuset_to_gtl.r")
source("helper_functions/load_analyses.r")
source("helper_functions/save_analyses_objects.r")
source("helper_functions/create_annotations.r")

