run_topGO_reactome <- function(de_container = NULL,
                      res_de = NULL,
                      de_genes = NULL,
                      bg_genes = NULL,
                      top_de = NULL,
                      FDR_threshold = 0.05,
                      min_counts = 0,
                      ontology = "BP", # could use also "MF"
                      annot = annFUN.org, # parameters for creating topGO object
                      mapping = "org.Mm.eg.db",
                      gene_id = "symbol", # could also be = "entrez"
                      full_names_in_rows = TRUE,
                      add_gene_to_terms = TRUE,
                      de_type = "up_and_down",
                      topGO_method2 = "elim",
                      do_padj = FALSE,
                      verbose = TRUE) {
  ## Checks:

  # Check if de-type is correct

  de_type <- match.arg(
    de_type,
    choices = c("up_and_down", "up", "down"),
    several.ok = FALSE)

  # Check if there is any input at all
  if (is.null(c(de_genes, bg_genes, de_container, res_de))) {
    stop(
      "Please provide one of the following forms of input: \n",
      "A vector of differentially expressed genes and a vector of backgoud genes. \n",
      "A DEseqDataset  and a DESeqResults generated by DESeq2."
    )
  }

  # Check if there only a res_de is given
  if (!is.null(res_de) & is.null(de_container)) {
    stop("Please also provide a de_container such as a DESeq2Dataset object.")
  }

  # check if only de_container is given
  if (!is.null(de_container) & is.null(res_de)) {
    stop("Please also provide a DESeq2 result object.")
  }

  # Check if there only a bg but no de genes is given
  if (!is.null(bg_genes) & is.null(de_genes)) {
    stop("Please also provide a vector of  differentially expressed genes.")
  }

  # Check if there is only a de but no bg genes given
  if (!is.null(de_genes) & is.null(bg_genes)) {
    stop("Please also provide  a vector of background genes.")
  }


  # checking the additional topGO_method2
  topgo_methods <- c("elim", "weight", "weight01", "lea", "parentchild")
  if (!(topGO_method2 %in% topgo_methods)) {
    stop(
      "Please provide one of the following topGO methods in addition to the classic method:\n",
      paste(topgo_methods, collapse = ", ")
    )
  }

  # Check if de_type is used with vectors and if so stop the function to avoid false interpretation of the
  # results. de_type needs the L2FC to determine up/down regulation. It can't be used with vectors.
  if ((de_type == "up" | de_type == "down") && !is.null(de_genes)) {
    stop(
      "The argument de_type can only be used if a de_container and a res_de object are provided:\n",
      "please either provide these objects or if you want to work with gene vectors set de_type to: 'up_and_down'"
    )
  }

  annot_to_map_to <- get(mapping)

  if (!is.null(res_de) && !is.null(de_container)) {
    # Check if the inputs are the correct type

    if (!is(de_container, "DESeqDataSet")) {
      stop("The provided `de_container` is not a DESeqDataSet object, please check your input parameters.")
    }

    if (!is(res_de, "DESeqResults")) {
      stop("The provided `res_de` is not a DESeqResults object, please check your input parameters.")
    }

    # checking that results and de_container are related
    ## at least a subset of de_container should be in res
    if (!all(rownames(res_de) %in% rownames(de_container))) {
      warning(
        "It is likely that the provided `de_container` and `res_de` objects are not related ",
        "to the same dataset (the row names of the results are not all in the de_container). ",
        "Are you sure you want to proceed?"
      )
    }

    # Check if DESeq was run on the de_container
    if (!"results" %in% mcols(mcols(de_container))$type) {
      stop("I couldn't find results in your de_container. You should first run DESeq2::DESeq() on your de_container.")
    }

    res_de$symbol <- AnnotationDbi::mapIds(annot_to_map_to,
                                           keys = row.names(res_de),
                                           column = "SYMBOL",
                                           keytype = "ENSEMBL",
                                           multiVals = "first"
    )

    resOrdered <- as.data.frame(res_de[order(res_de$padj), ])

    if (de_type == "up_and_down") {
      de_df <- resOrdered[resOrdered$padj <= FDR_threshold & !is.na(resOrdered$padj), ]
    } else if (de_type == "up") {
      de_df <- resOrdered[resOrdered$padj <= FDR_threshold & !is.na(resOrdered$padj), ]
      de_df <- de_df[de_df$log2FoldChange >= 0, ]
    } else if (de_type == "down") {
      de_df <- resOrdered[resOrdered$padj <= FDR_threshold & !is.na(resOrdered$padj), ]
      de_df <- de_df[de_df$log2FoldChange <= 0, ]
    }
    de_genes <- de_df$symbol
    if (!is.null(top_de)) {
      top_de <- min(top_de, length(de_genes))
      de_genes <- de_genes[seq_len(top_de)]
    }
    bg_ids <- rownames(de_container)[rowSums(counts(de_container)) > min_counts]
    bg_genes <- AnnotationDbi::mapIds(annot_to_map_to,
                                      keys = bg_ids,
                                      column = "SYMBOL",
                                      keytype = "ENSEMBL",
                                      multiVals = "first"
    )
    if (verbose) {
      .info_enrichrun(n_de = nrow(de_df),
                      n_de_selected = length(de_genes),
                      de_type = de_type,
                      res_de = res_de)
    }
  } else if (!is.null(c(bg_genes, de_genes))) {
    all_de <- length(de_genes)

    if (!is.null(top_de)) {
      top_de <- min(top_de, length(de_genes))
      de_genes <- de_genes[seq_len(top_de)]
    }
    if (verbose) {
      .info_enrichrun(n_de = all_de,
                      n_de_selected = length(de_genes),
                      de_type = de_type,
                      res_de = NULL)
    }
  }

  # creating the vectors
  de_genes_input <- factor(as.integer(bg_genes %in% de_genes))
  names(de_genes_input) <- bg_genes

  # instantiating the topGOdata object
  suppressMessages({
    GOdata <- new("topGOdata",
                  ontology = ontology,
                  allGenes = de_genes_input,
                  nodeSize = 10,
                  annot = annot,
                  mapping = mapping,
                  ID = gene_id
    )
  })
  # performing the test(s)
  suppressMessages({
    result_method2 <- runTest(GOdata, algorithm = topGO_method2,
                              statistic = "fisher")
  })
  suppressMessages({
    resultClassic <- runTest(GOdata, algorithm = "classic",
                             statistic = "fisher")
  })
  sTab <- GenTable(GOdata,
                   p.value_method2 = result_method2,
                   p.value_classic = resultClassic,
                   orderBy = "p.value_method2",
                   ranksOf = "p.value_classic",
                   topNodes = length(score(resultClassic))
  )

  names(sTab)[which(names(sTab) == "p.value_method2")] <-
    paste0("p.value_", topGO_method2)

  sTab[["p.value_classic"]] <- as.numeric(sTab[["p.value_classic"]])
  sTab[[paste0("p.value_", topGO_method2)]] <-
    as.numeric(sTab[[paste0("p.value_", topGO_method2)]])

  # if FDR, then apply it here
  if (do_padj) {
    sTab[[paste0("padj_BY_", topGO_method2)]] <-
      p.adjust(sTab[[paste0("p.value_", topGO_method2)]], method = "BY")
  }

  # subset to specified number of rows

  topTablerows <- nrow(sTab)
  sTab <- sTab[seq_len(topTablerows), ]

  if (full_names_in_rows) {
    sTab$Term <- vapply(sTab$GO.ID, function(go) {
      Term(GOTERM[[go]])
    }, FUN.VALUE = character(1))
  }

  if (add_gene_to_terms) {
    # adapted from an elegant one liner found here: https://support.bioconductor.org/p/65856/
    SignificantGenes <- sigGenes(GOdata)
    sTab$genes <- lapply(sTab$GO.ID, function(x) {
      genes <- genesInTerm(GOdata, x)
      tmp <- genes[[1]][genes[[1]] %in% SignificantGenes]
    })
    # coerce the list to a comma separated vector
    sTab$genes <- unlist(lapply(sTab$genes, function(arg) paste(arg, collapse = ",")))
  }
  # message for filters or a summary here
  message(
    nrow(sTab),
    " GO terms were analyzed. Not all of them are significantly enriched.\n",
    "We suggest further subsetting the output list by for example: \n",
    "using a pvalue cutoff in the column: \n",
    "'p.value_elim'."
  )

  return(sTab)
}

